{% set name = "ufolint" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ufolint-{{ version }}.tar.gz
  sha256: 5578c2a17949b33e9a9d2d069849f7a83ca82b5f0a3d35bef8d24668be95bbe7

build:
  entry_points:
    - ufolint = ufolint.app:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - commandlines
    - fonttools >=4.18.0
    - python >={{ python_min }}
    - fs

test:
  imports:
    - ufolint
  commands:
    - pip check
    - ufolint --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/source-foundry/ufolint
  summary: UFO source file linter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
